services:
  web:
    # build: .
    image: 1314spb/ie_fyp-web:latest
    ports:
      - "80:3000"
    env_file:
      - ./Server/.env
    networks:
      - internal
    volumes:
      - ./:/app
    depends_on:
      - db
      - ai

  ai:
    image: 1314spb/ie_fyp-ai:latest
    ports:
      - "8000:8000"
    env_file:
      - ./AI/.env
    networks:
      - internal
    volumes:
      - ./AI:/app
    depends_on:
      - db


  db:
    # image: mysql:latest
    image: 1314spb/ie_fyp-db:latest
    ports:
      - "3307:3306"
    env_file:
      - ./Database/docker_db/.env
    networks:
      - internal
    volumes:
      - ./Database/docker_db/db_data:/var/lib/mysql
      - ./Database/docker_db:/docker-entrypoint-initdb.d

networks:
  internal:
