services:
  web:
    build: .
    ports:
      - "80:3000"
    env_file:
      - ./Server/.env
    networks:
      - internal
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    env_file:
      - ./Database/docker_db/.env
    networks:
      - internal
    volumes:
      - ./Database/docker_db/db_data:/var/lib/mysql
      - ./Database/docker_db:/docker-entrypoint-initdb.d

networks:
  internal:
  